_wandb:
    value:
        cli_version: 0.22.3
        e:
            rw31zxyffivfmhsrmmbl5f8k8x4mljce:
                codePath: ml_pipeline/evaluation/bias_detection.py
                codePathLocal: ml_pipeline/evaluation/bias_detection.py
                email: group9mlops@gmail.com
                executable: /Users/sriks/.pyenv/versions/frontshiftai/bin/python
                git:
                    commit: 7be0d9fd4d3f9aabbbdf3b86e7b1b18b0b0ec9e4
                    remote: https://github.com/sriksven/FrontShiftAI.git
                host: Krishnas-MacBook-Pro.local
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/sriks/Documents/Projects/FrontShiftAI/ml_pipeline/evaluation/bias_detection.py
                python: CPython 3.12.9
                root: /Users/sriks/Documents/Projects/FrontShiftAI
                startedAt: "2025-11-02T20:28:42.039032Z"
                writerId: rw31zxyffivfmhsrmmbl5f8k8x4mljce
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": darwin-arm64
model_name:
    value: llama_3b_instruct
stage:
    value: Bias_Detection
