_wandb:
    value:
        cli_version: 0.22.3
        e:
            y84htdh4lpz1dpoyfujnab71i942z922:
                codePath: ml_pipeline/evaluation/sensitivity_analysis.py
                codePathLocal: ml_pipeline/evaluation/sensitivity_analysis.py
                email: group9mlops@gmail.com
                executable: /Users/sriks/.pyenv/versions/frontshiftai/bin/python
                git:
                    commit: 7439936a1181d8c2e603a578cc557b50a1c9f8fe
                    remote: https://github.com/sriksven/FrontShiftAI.git
                host: Krishnas-MacBook-Pro.local
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/sriks/Documents/Projects/FrontShiftAI/ml_pipeline/evaluation/sensitivity_analysis.py
                python: CPython 3.12.9
                root: /Users/sriks/Documents/Projects/FrontShiftAI
                startedAt: "2025-11-02T19:55:53.739977Z"
                writerId: y84htdh4lpz1dpoyfujnab71i942z922
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 75
                - 92
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 75
                - 92
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.3
            "6": 4.45.2
            "10":
                - 20
            "12": 0.22.3
            "13": darwin-arm64
model_name:
    value: llama_3b_instruct
stage:
    value: Sensitivity_Analysis
