_wandb:
    value:
        cli_version: 0.22.3
        e:
            t442bo0x2o7002phh7qazq7w16xx2dv1:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "11811160064"
                codePath: ml_pipeline/evaluation/unified_eval_summary.py
                codePathLocal: ml_pipeline/evaluation/unified_eval_summary.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "310095405056"
                email: group9mlops@gmail.com
                executable: /Users/sriks/.pyenv/versions/frontshiftai/bin/python
                git:
                    commit: 7be0d9fd4d3f9aabbbdf3b86e7b1b18b0b0ec9e4
                    remote: https://github.com/sriksven/FrontShiftAI.git
                host: Krishnas-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/sriks/Documents/Projects/FrontShiftAI/ml_pipeline/evaluation/unified_eval_summary.py
                python: CPython 3.12.9
                root: /Users/sriks/Documents/Projects/FrontShiftAI
                startedAt: "2025-11-02T20:29:01.454682Z"
                writerId: t442bo0x2o7002phh7qazq7w16xx2dv1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": darwin-arm64
model_name:
    value: llama_3b_instruct
stage:
    value: Unified_Evaluation_Visualization
